package com.qali.aterm.agent.utils

/**
 * Represents a structured upgrade plan generated by AI
 */
data class UpgradePlan(
    /**
     * Summary of the upgrade request
     */
    val summary: String,
    
    /**
     * List of files that need to be modified
     */
    val filesToModify: List<FileChange>,
    
    /**
     * List of new files that need to be created
     */
    val filesToCreate: List<NewFile>,
    
    /**
     * List of dependencies that need to be updated
     */
    val dependenciesToUpdate: List<DependencyUpdate>,
    
    /**
     * Step-by-step execution plan
     */
    val executionSteps: List<ExecutionStep>,
    
    /**
     * Risk assessment of the upgrade
     */
    val riskAssessment: RiskAssessment? = null,
    
    /**
     * Estimated effort/complexity
     */
    val estimatedEffort: String? = null
)

/**
 * Represents a file that needs to be modified
 */
data class FileChange(
    val filePath: String,
    val changeType: ChangeType,
    val description: String,
    val affectedFunctions: List<String> = emptyList(),
    val affectedClasses: List<String> = emptyList(),
    val estimatedLinesChanged: Int? = null
)

/**
 * Represents a new file that needs to be created
 */
data class NewFile(
    val filePath: String,
    val fileType: String, // "code", "config", "test", etc.
    val description: String,
    val dependencies: List<String> = emptyList() // Files this depends on
)

/**
 * Represents a dependency update
 */
data class DependencyUpdate(
    val packageName: String,
    val currentVersion: String? = null,
    val targetVersion: String? = null,
    val updateType: DependencyUpdateType,
    val reason: String
)

/**
 * Type of file change
 */
enum class ChangeType {
    MODIFY,      // Modify existing code
    REFACTOR,    // Refactor existing code
    ADD_FEATURE, // Add new feature to existing file
    REMOVE,      // Remove code/feature
    REPLACE      // Replace entire section
}

/**
 * Type of dependency update
 */
enum class DependencyUpdateType {
    ADD,         // Add new dependency
    UPDATE,      // Update existing dependency
    REMOVE,      // Remove dependency
    REPLACE      // Replace with alternative
}

/**
 * Execution step in the upgrade plan
 */
data class ExecutionStep(
    val stepNumber: Int,
    val description: String,
    val action: String, // "modify", "create", "update", "test"
    val target: String, // File path or dependency name
    val prerequisites: List<Int> = emptyList() // Step numbers that must complete first
)

/**
 * Risk assessment for the upgrade
 */
data class RiskAssessment(
    val overallRisk: RiskLevel,
    val breakingChanges: List<String> = emptyList(),
    val potentialIssues: List<String> = emptyList(),
    val recommendations: List<String> = emptyList()
)

/**
 * Risk level
 */
enum class RiskLevel {
    LOW,      // Low risk, safe to proceed
    MEDIUM,   // Medium risk, proceed with caution
    HIGH,     // High risk, review carefully
    CRITICAL  // Critical risk, may break functionality
}
